#!/bin/sh
launchStream() {
    streamlink https://www.twitch.tv/$1 best --twitch-disable-ads &
}

if [[ -z "$@" ]] ;
    then 
        echo 'Enter runner names'
        read runners

        for runner in $runners ;
            do launchStream $runner
        done
    else
        for runner in "$@" ;
            do launchStream $runner
        done
fi

