#!/bin/sh

if [[ -z $SOURCE_FOLDER ]] ;
	then echo 'Expected environment variable $SOURCE_FOLDER'
	exit 1
fi
currentDir=$(pwd)

cd $SOURCE_FOLDER

for d in */; do
    cd $d
    if git rev-parse --is-inside-work-tree > /dev/null 2>&1;
    then
        echo "fetching $d"
        git fetch -pt --all
        cd ..
    else
        for sd in */; do
            cd $sd
            if git rev-parse --is-inside-work-tree > /dev/null 2>&1;
            then
                echo "fetching $sd"
                git fetch -pt --all
                cd ..
            else
                echo "$sd is not a git directory."
                cd ..
            fi
        done
        cd ..
    fi
done

cd $currentDir
