#!/bin/sh

if [[ -z $1 ]] ;
	then echo 'must supply a new repository name'
	exit 1

fi

if [[ -z $GITHUB_ACCESS_TOKEN ]] ;
	then echo 'Expected environment variable $GITHUB_ACCESS_TOKEN'
	exit 1
fi

if [[ -z $GITHUB_USERNAME ]] ;
	then echo 'Expected environment variable $GITHUB_USERNAME'
	exit 1
fi

curl -H "Authorization: token $GITHUB_ACCESS_TOKEN" https://api.github.com/user/repos -d "{\"name\": \"$1\"}"

git init
git remote add origin git@github.com:$GITHUB_USERNAME/$1.git

git checkout -b main

echo $1 >> README.md

git add README.md
git commit -m "creating main branch for $1"

git push -u origin main
